version: '3'

services:

    app:
        build: .
        container_name: roraima-app
        volumes:
            - .:/var/www
        #depends_on:
        #  db:
        #    condition: service_healthy

    nginx:
        build: .docker/nginx
        container_name: roraima-nginx
        restart: always
        tty: true
        ports:
            - "8000:80"
        volumes:
            - .:/var/www

    # db:
    #     image: mysql:5.7
    #     command: --innodb-use-native-aio=0
    #     container_name: roraima-db
    #     restart: always
    #     tty: true
    #     ports:
    #         - "3308:3306"
    #     volumes:
    #       - ./.docker/dbdata:/var/lib/mysql
    #     environment:
    #         - MYSQL_DATABASE=laravel
    #         - MYSQL_ROOT_PASSWORD=root
    #         - MYSQL_USER=root
    #     networks:
    #       - app-network
        #healthcheck:
        #  test: ["CMD-SHELL", 'mysql -uroot --database=laravel --password=root --execute="SELECT count(table_name) > 0 FROM information_schema.tables;" --skip-column-names -B']
        #  interval: 10s
        #  timeout: 10s
        #  retries: 4

    # redis:
    #     image: redis:alpine
    #     container_name: roraima-redis
    #     expose:
    #         - 6379
        
networks:
    app-network:
        driver: bridge